version: '3.8'

services:
  antvis-mcp:
    image: antvis-chart-sse:latest
    ports:
      - "7001:7001"
    environment:
      - PORT=7001
      - ENDPOINT=/message
      - NODE_ENV=production
      - HOST=192.168.10.187
      - LOG_LEVEL=info
      - IMAGES_DIR=/app/images
      - MAX_IMAGE_SIZE=10
    volumes:
      - ./images:/app/images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 