version: '3.8'

services:
  chart-render:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ENDPOINT=/message
      - NODE_ENV=production
    volumes:
      - ./images:/app/images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/message"]
      interval: 30s
      timeout: 10s
      retries: 3 