version: '3.8'

services:
  antvis-mcp:
    container_name: antvis-mcp
    image: antvis-mcp-sse:latest
    user: "1000:1000"  # 映射到宿主机用户ID
    ports:
      - "8000:8000" # HTTP端口
      - "8443:8443" # HTTPS端口
    environment:
      - HTTP_PORT=8000
      - HTTPS_PORT=8443
      - ENDPOINT=/message
      - NODE_ENV=production
      - HOST=192.168.10.187
      - ENABLE_HTTPS=false            # 启用HTTPS服务器
      - ENABLE_HTTP=true              # 启用HTTP服务器
      - LOG_LEVEL=info
      - IMAGES_DIR=/app/images
      - MAX_IMAGE_SIZE=10
      # SSL证书配置（可选，不配置则使用自签名证书）
      # - SSL_KEY_PATH=/app/ssl/external.key
      # - SSL_CERT_PATH=/app/ssl/external.crt
    volumes:
      - ./images:/app/images
      - ./ssl:/app/ssl              # SSL证书目录挂载（可选）
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 